Name: Manthan Solanki

ID:   202318012

In [2]:
import sklearn
from sklearn.datasets import fetch_20newsgroups
import pandas as pd
import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


1. You need to implement a TF-IDF vectorizer to convert a collection of documents 
into TF-IDF vectors. You can use the sklearn’s inbuild datase        
fetch_20newsgroups.

In [3]:
# for vectorizing documents
def get_vecs(data):
    
    # vectorizing data 
    
    vec = TfidfVectorizer(stop_words = 'english')
    mat = vec.fit_transform(data)
    return mat

# fetching data from built-in sklearn dataset
    
data = fetch_20newsgroups(subset='train')
# data = data['data']

tfidf_vecs = get_vecs(data['data'])
print('TD-IDF vectors:  ')
print(tfidf_vecs)

TD-IDF vectors:  
  (0, 86416)	0.14330464297977982
  (0, 35135)	0.10188109676312235
  (0, 65968)	0.10658183340971177
  (0, 114195)	0.06002582888934523
  (0, 78809)	0.06524029473980168
  (0, 76578)	0.0752490171119318
  (0, 57203)	0.16977226500364592
  (0, 67023)	0.07965653370342658
  (0, 63238)	0.09086750717799585
  (0, 95944)	0.11792442679286105
  (0, 127721)	0.0660283455431985
  (0, 109044)	0.11811852219269026
  (0, 51651)	0.10581100308545811
  (0, 83103)	0.09633120317294654
  (0, 113755)	0.1926949257821117
  (0, 73061)	0.04662587301170703
  (0, 34131)	0.09493746671845804
  (0, 101175)	0.08899924936054199
  (0, 105907)	0.10749912859686628
  (0, 35560)	0.1446512460011004
  (0, 26070)	0.10385185139503332
  (0, 108033)	0.08197182211166716
  (0, 99619)	0.06171903092868097
  (0, 48552)	0.1263844988551673
  (0, 34943)	0.18203649549572573
  :	:
  (11313, 106061)	0.11739285034416508
  (11313, 67469)	0.07888902121089117
  (11313, 63763)	0.11511167728184264
  (11313, 37359)	0.16552340600580592


2. Create a function to calculate the cosine similarity between two TF-IDF vectors.

In [9]:
# to get cosine similarity

def get_csn_sim(v1, v2):
    csn_sim = cosine_similarity(v1, v2)
    return csn_sim
    

tfidf_vecs = get_vecs(data['data'])

# comparing two random documents from dataset

ind1 = np.random.randint(0, tfidf_vecs.shape[0])
ind2 = np.random.randint(0, tfidf_vecs.shape[0])

print('\nDocument 1: ', data['data'][ind1][:100])
print('\nDocument 2: ', data['data'][ind2][:100])

# cosine similarity between two docs

csn_sim = get_csn_sim(tfidf_vecs[ind1], tfidf_vecs[ind2])
csn_sim = np.round(csn_sim[0][0], 6) 
print('\nCosine Similarity between docs: ', csn_sim)



Document 1:  From: aa229@Freenet.carleton.ca (Steve Birnbaum)
Subject: Re: rejoinder. Questions to Israelis
Reply

Document 2:  From: rrn@po.CWRU.Edu (Robert R. Novitskey)
Subject: The "P24T"
Organization: Case Western Reserve U

Cosine Similarity between docs:  0.007025


In [8]:

idx = np.array([x for x in range(tfidf_vecs.shape[0])])

# splitting documents into train and test to get similarity
train_idx = np.random.choice(idx, size = int(0.8 * (tfidf_vecs.shape[0])), replace = False)
test_idx = np.setdiff1d(idx, train_idx)

train = tfidf_vecs[train_idx]
test = tfidf_vecs[test_idx]

csn_sim = cosine_similarity(train, test)
csn_sim = np.round(csn_sim, 6) 
print('\nCosine Similarity between all docs: \n\n', csn_sim)



Cosine Similarity between all docs: 

 [[0.005075 0.003693 0.004547 ... 0.003033 0.009611 0.006038]
 [0.008745 0.014985 0.002162 ... 0.002752 0.007665 0.000853]
 [0.046965 0.008516 0.002519 ... 0.041996 0.000728 0.009717]
 ...
 [0.022131 0.010423 0.008925 ... 0.004424 0.005731 0.013659]
 [0.014192 0.043459 0.025256 ... 0.006072 0.006742 0.020782]
 [0.012188 0.00103  0.034731 ... 0.018326 0.014238 0.000485]]


3. Implement a document similarity search function that takes a document as input
and returns a list of documents ranked by their similarity to the input document.

In [10]:
# document similarity search function

def doc_sim(idx):

    data = fetch_20newsgroups(subset='train')
    docs = data['data']
    d = docs[idx]
    
    docs.pop(idx)
    vec = TfidfVectorizer(stop_words = 'english')
    train = vec.fit_transform(docs)
    test = vec.transform([d])

    csn_sim = cosine_similarity(train, test)
    print('\nCosine similarity matrix: \n\n', csn_sim)
    indices = np.arange(len(csn_sim)).astype('int')
    
    sim_idx = np.argsort(csn_sim, axis=0).flatten()
    print('\nDocument indices sorted by index rank: \n', sim_idx)
    top_5 = sim_idx.argsort()[:-6:-1]
    print('\nMin. document indices: ',   top_5)
    
    res = [docs[i][:100] for i in top_5]
    
    return np.array (res)

In [16]:

idx = np.random.randint(0, len(data['data']))
print('\nQuery Document to search: \n\n: ', data['data'][idx][:100])

doc = doc_sim(idx)

print("\nList of Most Similar Documents by ranking: \n")
for i in range (len(doc)):
    print(f'\n{i+1}. {doc[i]}')



Query Document to search: 

:  From: lady@uhunix.uhcc.Hawaii.Edu (Lee Lady)
Subject: Re: Science and Methodology
Summary: Merely av

Cosine similarity matrix: 

 [[0.01167803]
 [0.01063482]
 [0.0219113 ]
 ...
 [0.00201654]
 [0.02942423]
 [0.00673224]]

Document indices sorted by index rank: 
 [4772 8665 9080 ... 3705 5912 4471]
Min. document indices:  [ 2523 10326   424  2372  1358]

List of Most Similar Documents by ranking: 


1. From: envbvs@epb11.lbl.gov (Brian V. Smith)
Subject: Re: I need source for splines
Article-I.D.: dog

2. From: amanda@intercon.com (Amanda Walker)
Subject: Re: Secret algorithm [Re: Clipper Chip and crypto

3. From: keith@cco.caltech.edu (Keith Allan Schneider)
Subject: Re: <Political Atheists?
Organization: 

4. From: cdt@sw.stratus.com (C. D. Tavares)
Subject: Re: The 'pill' for Deer = No Hunting
Organization:

5. From: dbrooks@osf.org (David Brooks)
Subject: Re: Q: Colormaps with dialog shells
Organization: Open
